# Generated by Django 2.0.7 on 2018-07-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20180729_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cancelations',
            new_name='cancellations',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='listing',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_image'),
        ),
    ]
