# Generated by Django 2.0.7 on 2018-07-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20180730_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
