# Generated by Django 2.0.7 on 2018-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_auto_20180731_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='platform_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ical_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
